### ISSUE TITLE
Unable to run make or python scripts

### ISSUE THREAD

**Issue by simstra** [zeromq/f77_zmq#12]
Hi!

I've downloaded and installed zeromq according to the instructions on 

http://zeromq.org/intro:get-the-software

Then I've cloned your repo and tried to install it via the make command, resulting in the following output:

```
gcc -fPIC  -O3 -fPIC -Wall -pedantic -g -c f77_zmq.c -o f77_zmq.o
f77_zmq.c: In function ‘f77_zmq_ctx_new_’:
f77_zmq.c:76:12: warning: implicit declaration of function ‘zmq_ctx_new’ [-Wimplicit-function-declaration]
     return zmq_ctx_new ();
            ^
f77_zmq.c:76:12: warning: return makes pointer from integer without a cast [-Wint-conversion]
f77_zmq.c: In function ‘f77_zmq_ctx_term_’:
f77_zmq.c:81:12: warning: implicit declaration of function ‘zmq_ctx_term’ [-Wimplicit-function-declaration]
     return zmq_ctx_term (*context);
            ^
f77_zmq.c: In function ‘f77_zmq_ctx_shutdown_’:
f77_zmq.c:86:12: warning: implicit declaration of function ‘zmq_ctx_shutdown’ [-Wimplicit-function-declaration]
     return zmq_ctx_shutdown (*context);
            ^
f77_zmq.c: In function ‘f77_zmq_ctx_get_’:
f77_zmq.c:91:10: warning: implicit declaration of function ‘zmq_ctx_get’ [-Wimplicit-function-declaration]
   return zmq_ctx_get (*context, *option_name );
          ^
f77_zmq.c: In function ‘f77_zmq_ctx_set_’:
f77_zmq.c:96:10: warning: implicit declaration of function ‘zmq_ctx_set’ [-Wimplicit-function-declaration]
   return zmq_ctx_set (*context, *option_name, *option_value);
          ^
f77_zmq.c: In function ‘f77_zmq_ctx_destroy_’:
f77_zmq.c:107:12: warning: implicit declaration of function ‘zmq_ctx_destroy’ [-Wimplicit-function-declaration]
     return zmq_ctx_destroy (*context);
            ^
f77_zmq.c: In function ‘f77_zmq_unbind_’:
f77_zmq.c:160:8: warning: implicit declaration of function ‘zmq_unbind’ [-Wimplicit-function-declaration]
   rc = zmq_unbind (*socket, address);
        ^
f77_zmq.c: In function ‘f77_zmq_disconnect_’:
f77_zmq.c:203:8: warning: implicit declaration of function ‘zmq_disconnect’ [-Wimplicit-function-declaration]
   rc = zmq_disconnect (*socket, address);
        ^
f77_zmq.c: In function ‘f77_zmq_socket_monitor_’:                                                              
f77_zmq.c:235:8: warning: implicit declaration of function ‘zmq_socket_monitor’ [-Wimplicit-function-declaration]                                                                                                             
   rc = zmq_socket_monitor(*socket,address,*events);                                                           
        ^                                                                                                      
f77_zmq.c: In function ‘f77_zmq_send_’:                                                                        
f77_zmq.c:245:10: error: too many arguments to function ‘zmq_send’                                             
   return zmq_send (*socket, message, *message_len, *flags);                                                   
          ^                                                                                                    
In file included from f77_zmq.c:27:0:                                                                          
zmq.h:229:16: note: declared here                                                                              
 ZMQ_EXPORT int zmq_send (void *s, zmq_msg_t *msg, int flags);                                                 
                ^                                                                                              
f77_zmq.c: In function ‘f77_zmq_send_const_’:                                                                  
f77_zmq.c:250:10: warning: implicit declaration of function ‘zmq_send_const’ [-Wimplicit-function-declaration] 
   return zmq_send_const (*socket, message, *message_len, *flags);                                             
          ^
f77_zmq.c: In function ‘f77_zmq_recv_’:
f77_zmq.c:255:10: error: too many arguments to function ‘zmq_recv’
   return zmq_recv (*socket, message, *message_len, *flags);
          ^
In file included from f77_zmq.c:27:0:
zmq.h:230:16: note: declared here
 ZMQ_EXPORT int zmq_recv (void *s, zmq_msg_t *msg, int flags);
                ^
f77_zmq.c: In function ‘f77_zmq_msg_send_’:
f77_zmq.c:329:11: warning: implicit declaration of function ‘zmq_msg_send’ [-Wimplicit-function-declaration]
    return zmq_msg_send (*msg, *socket, *flags);
           ^
f77_zmq.c: In function ‘f77_zmq_msg_recv_’:
f77_zmq.c:335:11: warning: implicit declaration of function ‘zmq_msg_recv’ [-Wimplicit-function-declaration]
    return zmq_msg_recv (*msg, *socket, *flags);
           ^
f77_zmq.c: In function ‘f77_zmq_msg_more_’:
f77_zmq.c:370:10: warning: implicit declaration of function ‘zmq_msg_more’ [-Wimplicit-function-declaration]
   return zmq_msg_more (*message);
          ^
f77_zmq.c: In function ‘f77_zmq_msg_get_’:
f77_zmq.c:376:10: warning: implicit declaration of function ‘zmq_msg_get’ [-Wimplicit-function-declaration]
   return zmq_msg_get (*message, *property);
          ^
f77_zmq.c: In function ‘f77_zmq_msg_gets_’:
f77_zmq.c:395:8: warning: implicit declaration of function ‘zmq_msg_gets’ [-Wimplicit-function-declaration]
   rc = zmq_msg_gets (*message, property);
        ^
f77_zmq.c:395:6: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   rc = zmq_msg_gets (*message, property);
      ^
f77_zmq.c: In function ‘f77_zmq_msg_set_’:
f77_zmq.c:403:10: warning: implicit declaration of function ‘zmq_msg_set’ [-Wimplicit-function-declaration]
   return zmq_msg_set (*message, *property, *value);
          ^
f77_zmq.c: In function ‘f77_zmq_proxy_’:
f77_zmq.c:465:10: warning: implicit declaration of function ‘zmq_proxy’ [-Wimplicit-function-declaration]
   return zmq_proxy(*frontend, *backend, *capture);
          ^
f77_zmq.c: In function ‘f77_zmq_proxy_steerable_’:
f77_zmq.c:471:10: warning: implicit declaration of function ‘zmq_proxy_steerable’ [-Wimplicit-function-declaration]
   return zmq_proxy_steerable(*frontend, *backend, *capture, *control);
          ^
Makefile:25: recipe for target 'f77_zmq.o' failed
make: *** [f77_zmq.o] Error 1

```

Therefore I tried copying zmq.h from /usr/include/zmq.h into the f77_zmq directory and running the python script manually, as recently discussed in the other issue posted [here](https://github.com/zeromq/f77_zmq/issues/10) . 

I'm running Ubuntu 16.04 and have tried both with Python 2.7.11 and 3.5.1. This is the error message I receive on both versions

```
Traceback (most recent call last):
  File "create_f77_zmq_h_py3.py", line 130, in <module>
    main()
  File "create_f77_zmq_h_py3.py", line 118, in main
    create_dict_of_defines(lines,file_out)
  File "create_f77_zmq_h_py3.py", line 59, in create_dict_of_defines
    exec(command, locals())
  File "<string>", line 1
    ZMQ_MSG_MASK=129 /* Merges all the flags */
                      ^
SyntaxError: invalid syntax
```
Any thought and ideas are welcome!

**Comment by scemama** [comment]
Thanks for your issue. I'll correct this very soon.

**Comment by scemama** [comment]
I can't reproduce your problem. This is what I did:
1) I downloaded a bootable Ubuntu 16.04 iso
2) I ran the iso in VirtualBox with the option "try before installing"
3) I downloaded zeromq-4.1.5 from here https://github.com/zeromq/zeromq4-1/releases/download/v4.1.5/zeromq-4.1.5.tar.gz
4) I ran `./configure ; make ; sudo make install` to install ZeroMQ. Note : the include files are in `/usr/local/include` and not in `/usr/include` by default
5) I downloaded the zip archive of f77_zmq here https://github.com/zeromq/f77_zmq/archive/master.zip
6) `export ZMQ_H=/usr/local/include/zmq.h`
7) make

And everything went fine. 

It seems to me that you have another version of ZeroMQ than a 4.0.x or 4.1.x. Can you tell me on which point your installation differs?
Thanks,
Anthony

**Comment by simstra** [comment]
I now realise I had installed the development master (I believe that is version 4.2 at the moment?) for zmq, so that might be why it did not work.

Upon running make in the f77_zmq-master folder with version 4.1.5 of zmq installed I get the output

```
cp /usr/local/include/zmq.h .
python2 create_f77_zmq_h.py zmq.h || python3 create_f77_zmq_h_py3.py zmq.h
===========================================
ZMQ_PTR set to 8 (for 64-bit architectures)
===========================================
gcc -fPIC  -O3 -fPIC -Wall -pedantic -g -c f77_zmq.c -o f77_zmq.o
gcc -fPIC  -shared f77_zmq.o -o libf77zmq.so
ar cr libf77zmq.a  f77_zmq.o

```
So everything seems to be working there now. Thank you! 

That takes us on to the next problem however. When going to the examples folder and running make again to try the hello world program I get the following output:

```
cp ../f77_zmq.h .
make -C ..
make[1]: Entering directory '/home/simon/Programming/f77_zmq-master'
make[1]: Nothing to be done for 'default'.
make[1]: Leaving directory '/home/simon/Programming/f77_zmq-master'
cp ../libf77zmq.a .
gfortran -g -O2 -Wall -Wno-unused -fopenmp hwserver.f -o hwserver libf77zmq.a -lzmq 
libf77zmq.a(f77_zmq.o): In function `f77_zmq_unbind_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:160: undefined reference to `zmq_unbind'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_disconnect_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:203: undefined reference to `zmq_disconnect'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_socket_monitor_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:235: undefined reference to `zmq_socket_monitor'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_msg_gets_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:395: undefined reference to `zmq_msg_gets'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_ctx_new_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:76: undefined reference to `zmq_ctx_new'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_ctx_term_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:81: undefined reference to `zmq_ctx_term'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_ctx_shutdown_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:86: undefined reference to `zmq_ctx_shutdown'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_ctx_get_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:91: undefined reference to `zmq_ctx_get'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_ctx_set_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:96: undefined reference to `zmq_ctx_set'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_ctx_destroy_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:107: undefined reference to `zmq_ctx_destroy'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_send_const_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:250: undefined reference to `zmq_send_const'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_msg_send_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:329: undefined reference to `zmq_msg_send'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_msg_recv_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:335: undefined reference to `zmq_msg_recv'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_msg_more_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:370: undefined reference to `zmq_msg_more'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_msg_get_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:376: undefined reference to `zmq_msg_get'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_msg_set_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:403: undefined reference to `zmq_msg_set'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_proxy_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:465: undefined reference to `zmq_proxy'
libf77zmq.a(f77_zmq.o): In function `f77_zmq_proxy_steerable_':
/home/simon/Programming/f77_zmq-master/f77_zmq.c:471: undefined reference to `zmq_proxy_steerable'
collect2: error: ld returned 1 exit status
Makefile:13: recipe for target 'hwserver' failed
make: *** [hwserver] Error 1


```
I've followed pretty much the exact installation steps you've described above, but something is still  going wrong somewhere.

**Comment by simstra** [comment]
I am however able to compile and run my own programs now, so the bindings for f77 are indeed working out alright when I copy the f77_zmq.h file into my project directory! Once again, thank you for your help, it is really appreciated! Please let me know if I can be of any assistance in troubleshooting the problems with the Makefile in your examples folder.

**Comment by scemama** [comment]
It seems to me that the library with which you link the examples (`-lzmq`) is probably not the library 4.1.5 you compiled, but some older version.
